version: "3.7"

services:
  app:
    container_name: app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    environment:
      - PORT=${PORT}
      - GOOGLE_BASE_URL=${GOOGLE_BASE_URL}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - X_API_KEY=${X_API_KEY}
    ports:
      - 4000:80
